# Experiment
exp_id: debug

# Paths
data_path: /media/DATA/Datasets/medseg_decathlon
output_dir: &output ../output

# Data
batch_size: &bsize 4
datagen:
    batch_size: *bsize
    img_dims: &dims !!python/tuple [50, 50, 50, 1]

# Model
model:
    name: 'DenseNet3D'
    trained_model: None
    compile_params:
        optimizer: Adam
        loss: categorical_crossentropy
        metrics: ['accuracy']

    model_params:
        blocks: [3, 6, 12]
        input_shape: *dims
        classes: 20

# Train parameters
train:
    ckpt_period: 2
    fit_params:
        epochs: 5
        steps_per_epoch: 302
        validation_steps: 20

