# Experiment
exp_id: debug_segment

# Paths
data_path: ../data_sliced
output_dir: &output ../output

# Data
batch_size: &bsize 32
datagen:
    batch_size: *bsize
    img_dims: &dims [320, 320, 2]

# Model
model:
    name: 'UNet2D'
    trained_model: None
    compile_params:
        optimizer: Adam
        loss: categorical_crossentropy
        metrics: ['accuracy']
    
    model_params:
        input_shape: *dims
        features: 32
        depth: 5
        conv_params:
            padding: same
            dropout: 0.0 
            batchnorm: True 
            dilation: !!python/tuple [1,1]

# Train parameters
train:
    ckpt_period: 2
    fit_params:
        epochs: 5
        steps_per_epoch: 1
        validation_steps: 1

# Test parameters
test:
    test_dir: ../data_test
    trained_model: ../output/debug_segment/checkpoints/wt-03-0.86.h5
    img_dims: *dims




