# Experiment
exp_id: debug_segment

# Paths
data_path: ../data_sliced
output_dir: &output ../output

# Data
batch_size: &bsize 32
datagen:
    batch_size: *bsize
    img_dims: &dims !!python/tuple [320, 320, 1]

# Model
model:
    name: 'UNet2D'
    trained_model: None
    compile_params:
        optimizer: Adam
        loss: dice_coef #categorical_crossentropy
        metrics: ['accuracy']
    
    model_params:
        input_shape: *dims
        features: 32
        depth: 5
        conv_params:
            padding: same
            dropout: 0.0 
            batchnorm: True 
            dilation: !!python/tuple [1,1]

# Train parameters
train:
    ckpt_period: 2
    fit_params:
        epochs: 2
        steps_per_epoch: 1
        validation_steps: 1

